import {Providers} from "./providers";
import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import "./globals.css";
import Navbar from "@/app/ui/navbar/navbar";

import { navbarButtons } from "./ui/navbar/constants/constants";

const roboto = Roboto({
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`relative ${roboto.className} antialiased`}
      >
        <Providers>
          <div className={`absolute z-1 size-[100%] bg-gradient-to-r from-indigo-500 
            via-purple-500 to-pink-500 opacity-20`}
          ></div>
          <div className="relative z-2 max-w-[1920px] min-h-[100vh] overflow-auto 
            p-1 flex gap-2
          ">
            <Navbar navbarButtons={navbarButtons}/>
            {children}
          </div>
        </Providers>
      </body>
    </html>
  );
}
